server:
  port: 8080

jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7

spring:
  datasource:
    url: jdbc:mysql://rm-bp137lbc7uuh69aqvxo.mysql.rds.aliyuncs.com:3306/sgzdbrollback?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: admin123
    password: ENC(TI8Gy+o1lCubkhgs3jNppOPHtQABnqCb)
  jackson:
    time-zone: GMT+8
    date_format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*Mapping.xml
  type-aliases-package: com.ben.sgzspringbootapi.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql